services:
  - type: web
    name: carpooling
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn everythingvit.wsgi"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
